version: '3.8'

services:
  db:
    image: postgres:15
    container_name: bq_manager_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bq_metadata_db
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: bq_manager_api
    volumes:
      - ./backend:/app
      - ../credentials.json:/app/credentials.json
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/bq_metadata_db
    env_file:
      - ../.env
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: bq_manager_ui
    volumes:
      - ./frontend:/app
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend
    ports:
      - "8501:8501"

volumes:
  postgres_data:
